### ISSUE TITLE
ソフトを完成させる

### ISSUE THREAD

**Issue by ujiuji54** [ujiuji54/D4-B_database#12]

**Comment by eeekcct** [comment]
今日は7時まで部活をしていたのでsortのやつは明日になると思います。
数値解析の時間内には終わると思うのでソフトウェアのレポートの提出はそのあとでも大丈夫でしょうか？

**Comment by ujiuji54** [comment]
OKです

**Comment by eeekcct** [comment]
降順昇順のソートできました。
sort_inf関数の変数を1つ追加しました。数字でソートするか文字でソートするかのbool型です。

**Comment by eeekcct** [comment]
masterのソートのバグを直した新しいブランチ作ったので確認しておいてください。
GUIへの表示はなくしてsort.txtに出力しています。

**Comment by ujiuji54** [comment]
テキストファイルに出力したのね
databaseに直接値を返すのは難しい？

**Comment by eeekcct** [comment]
GUIがmainからデータ受けとる引数がポインタとかなら直接上書きできると思う

**Comment by eeekcct** [comment]
色々試してみる

**Comment by eeekcct** [comment]
ソートしたものが表示されるようにしました。

**Comment by eeekcct** [comment]
databaseのfile_input関数を利用してdatabaseの値を変更させました。
file_inputを利用しないやつも作っときます。

**Comment by ujiuji54** [comment]
了解
またマージしておきます

**Comment by eeekcct** [comment]
よろしくお願いします。
今はソートしたのと元のデータを別のテキストファイルにいれてるけどソートのファイルっていらん？

**Comment by ujiuji54** [comment]
分ける必要ない気がする

**Comment by eeekcct** [comment]
じゃあ消しとくわ

**Comment by ujiuji54** [comment]
完成したらmasterにプルリク送って欲しいです

**Comment by eeekcct** [comment]
わかりました

**Comment by eeekcct** [comment]
プルリクエスト送りました。
sort.txtとかファイルに書き込む関数とか残してるけど消しても大丈夫です。

**Comment by eeekcct** [comment]
日本語入れたらスペースの幅がおかしくなる
